### ISSUE TITLE
Hide View data until search is perform prevents some widgets from showing

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#1124]
Like: Custom Content widgets, Show Pagination Info and Page Links.

Tested on GV 2.0.13.1

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/611553557/15684?folderId=408730

**Comment by zackkatz** [comment]
@soulseekah Can you fix this when you're available?

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/623753504/15922/

**Comment by soulseekah** [comment]
This is fixed already. Fixing some failed tests and will push the commit.

**Comment by rafaehlers** [comment]
This bug still persists on 2.0.14.1: http://take.ms/SAonl

Reported by: https://secure.helpscout.net/conversation/622526246/15892?folderId=408730

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/653916653/16567?folderId=408730

**Comment by zackkatz** [comment]
@soulseekah Can you take another pass at this?

**Comment by soulseekah** [comment]
Yep, very probably fixed.

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/666831945/16811?folderId=408730
